//! feature_demo — exercises most of the tz API surface.
//! Set TZ_OWNER_ID to restrict to your own user id.
//! usage: TZ_API_ID=<id> TZ_API_HASH=<hash> TZ_BOT_TOKEN=<token> zig build feature-demo

const std = @import("std");
const tz = @import("tz");
const tg = tz.types;
const f = tz.functions;
const h = tz.helpers;

var g_environ: std.process.Environ = .empty;

fn isAllowed(msg: tz.Msg) bool {
    const env = g_environ.getPosix("TZ_OWNER_ID") orelse return true;
    const owner_id = std.fmt.parseInt(i64, env, 10) catch return true;
    return switch (msg.raw.peer_id) {
        .PeerUser => |p| p.user_id == owner_id,
        else => false,
    };
}

fn stickerFilename(doc: tg.Document) []const u8 {
    for (doc.attributes) |attr| {
        switch (attr) {
            .DocumentAttributeFilename => |a| return a.file_name,
            else => {},
        }
    }
    if (std.mem.eql(u8, doc.mime_type, "video/webm")) return "sticker.webm";
    if (std.mem.eql(u8, doc.mime_type, "application/x-tgsticker")) return "sticker.tgs";
    return "sticker.webp";
}

// --- command handlers ---

fn onHelp(msg: tz.Msg) !void {
    var ft = h.FormattedText.init(msg.ctx.allocator);
    defer ft.deinit();
    try ft.bold("feature_demo");
    try ft.plain(" — tz API demo\n\n");
    const cmds = &[_][2][]const u8{
        .{ "/echo <text>", "echo in bold" },
        .{ "/fmt", "formatting demo" },
        .{ "/keyboard", "inline keyboard" },
        .{ "/document", "send a file" },
        .{ "/info", "your user info" },
        .{ "/react", "add ❤ (reply to msg)" },
        .{ "/unreact", "clear reactions (reply)" },
        .{ "/pin", "pin a message (reply)" },
        .{ "/unpin", "unpin a message (reply)" },
        .{ "/forward", "forward to this chat (reply)" },
    };
    for (cmds) |cmd| {
        try ft.code(cmd[0]);
        try ft.plain("  ");
        try ft.plain(cmd[1]);
        try ft.plain("\n");
    }
    try ft.plain("\nSend me a photo or sticker and I'll re-send it.");
    try msg.replyFmt(ft.text.items, ft.entities.items);
}

fn onEcho(msg: tz.Msg) !void {
    const arg = msg.text()["/echo ".len..];
    var ft = h.FormattedText.init(msg.ctx.allocator);
    defer ft.deinit();
    try ft.bold(arg);
    try msg.replyFmt(ft.text.items, ft.entities.items);
}

fn onFmt(msg: tz.Msg) !void {
    var ft = h.FormattedText.init(msg.ctx.allocator);
    defer ft.deinit();
    try ft.bold("bold");
    try ft.plain("  ");
    try ft.italic("italic");
    try ft.plain("  ");
    try ft.underline("underline");
    try ft.plain("  ");
    try ft.strike("strike");
    try ft.plain("  ");
    try ft.spoiler("spoiler");
    try ft.plain("\n");
    try ft.code("inline code");
    try ft.plain("\n");
    try ft.pre("pub fn main() !void {}\n", "zig");
    try ft.link("ziglang.org", "https://ziglang.org");
    try msg.replyFmt(ft.text.items, ft.entities.items);
}

fn onKeyboard(msg: tz.Msg) !void {
    const peer = msg.peer() orelse return;
    var row1 = [_]tz.unions.KeyboardButton{
        h.keyboard.callbackButton("Button A", "cb:a"),
        h.keyboard.callbackButton("Button B", "cb:b"),
    };
    var row2 = [_]tz.unions.KeyboardButton{
        h.keyboard.urlButton("ziglang.org", "https://ziglang.org"),
    };
    var rows = [_]tg.KeyboardButtonRow{
        h.keyboard.inlineRow(&row1),
        h.keyboard.inlineRow(&row2),
    };
    try msg.ctx.exec(f.messages.SendMessage{
        .peer = peer,
        .message = "Choose:",
        .reply_markup = .some(h.keyboard.inlineKeyboard(&rows)),
    });
}

fn onDocument(msg: tz.Msg) !void {
    const data = "feature_demo — test document\ngenerated by tz\n";
    try h.media.sendDocument(msg, data, "text/plain", .{ .caption = "demo.txt" });
}

fn onInfo(msg: tz.Msg) !void {
    const sender_id = msg.senderId() orelse return;
    var id_input = [_]tz.unions.InputUser{msg.ctx.entities.inputUser(sender_id) orelse return};
    const users_resp = try msg.ctx.call(f.users.GetUsers{ .id = &id_input });
    defer users_resp.deinit();
    if (users_resp.value.len == 0) return msg.reply("no result");
    const user = switch (users_resp.value[0]) {
        .User => |u| u,
        else => return msg.reply("unexpected user type"),
    };
    var ft = h.FormattedText.init(msg.ctx.allocator);
    defer ft.deinit();
    try ft.bold("user info\n");
    const id_str = try std.fmt.allocPrint(msg.ctx.allocator, "id: {d}\n", .{user.id});
    defer msg.ctx.allocator.free(id_str);
    try ft.plain(id_str);
    if (user.first_name.value) |n| {
        try ft.plain("first: ");
        try ft.plain(n);
        try ft.plain("\n");
    }
    if (user.last_name.value) |n| {
        try ft.plain("last: ");
        try ft.plain(n);
        try ft.plain("\n");
    }
    if (user.username.value) |n| {
        try ft.plain("username: @");
        try ft.plain(n);
        try ft.plain("\n");
    }
    if (user.bot.value != null) try ft.italic("(bot account)");
    try msg.replyFmt(ft.text.items, ft.entities.items);
}

fn onReact(msg: tz.Msg) !void {
    try h.addReaction(msg.ctx, msg.peer() orelse return, msg.replyToId() orelse msg.id(), "❤");
}

fn onUnreact(msg: tz.Msg) !void {
    try h.removeReaction(msg.ctx, msg.peer() orelse return, msg.replyToId() orelse msg.id());
}

fn onPin(msg: tz.Msg) !void {
    const target_id = msg.replyToId() orelse return msg.respond("reply to a message to pin it");
    try h.pinMessage(msg.ctx, msg.peer() orelse return, target_id, .{});
}

fn onUnpin(msg: tz.Msg) !void {
    const target_id = msg.replyToId() orelse return msg.respond("reply to a message to unpin it");
    try h.pinMessage(msg.ctx, msg.peer() orelse return, target_id, .{ .unpin = true });
}

fn onForward(msg: tz.Msg) !void {
    const target_id = msg.replyToId() orelse return msg.respond("reply to a message to forward it");
    const peer = msg.peer() orelse return;
    var ids = [_]i32{target_id};
    try h.forwardMessages(msg.ctx, peer, peer, &ids);
}

fn onMessage(msg: tz.Msg) !void {
    if (!isAllowed(msg)) return;

    if (msg.is("/start") or msg.is("/help")) return onHelp(msg);
    if (msg.prefix("/echo ")) return onEcho(msg);
    if (msg.is("/fmt")) return onFmt(msg);
    if (msg.is("/keyboard")) return onKeyboard(msg);
    if (msg.is("/document")) return onDocument(msg);
    if (msg.is("/info")) return onInfo(msg);
    if (msg.is("/react")) return onReact(msg);
    if (msg.is("/unreact")) return onUnreact(msg);
    if (msg.is("/pin")) return onPin(msg);
    if (msg.is("/unpin")) return onUnpin(msg);
    if (msg.is("/forward")) return onForward(msg);

    switch (msg.raw.media.value orelse return) {
        .MessageMediaPhoto => {
            const bytes = try h.download(msg.ctx, msg.mediaLocation() orelse return);
            defer msg.ctx.allocator.free(bytes);
            try h.media.sendDocument(msg, bytes, "image/jpeg", .{ .caption = "re-sent photo" });
        },
        .MessageMediaDocument => |md| {
            const doc = switch (md.document.value orelse return) {
                .Document => |d| d,
                else => return,
            };
            const is_sticker = for (doc.attributes) |a| {
                if (a == .DocumentAttributeSticker) break true;
            } else false;
            if (!is_sticker) return;
            const bytes = try h.download(msg.ctx, msg.mediaLocation() orelse return);
            defer msg.ctx.allocator.free(bytes);
            try h.media.sendDocument(msg, bytes, doc.mime_type, .{ .caption = stickerFilename(doc) });
        },
        else => {},
    }
}

fn onCallback(ctx: tz.Context, update: tg.UpdateBotCallbackQuery) !void {
    const data = update.data.value orelse return;
    if (std.mem.eql(u8, data, "cb:a")) {
        try h.answerCallbackQuery(ctx, update, .{ .text = "You pressed A!" });
    } else if (std.mem.eql(u8, data, "cb:b")) {
        try h.answerCallbackQuery(ctx, update, .{ .text = "You pressed B!", .alert = true });
    } else {
        try h.answerCallbackQuery(ctx, update, .{});
    }
}

const handlers = &.{
    tz.Msg.handler(onMessage),
    tz.handler(tg.UpdateBotCallbackQuery, onCallback),
};

pub fn main(init: std.process.Init.Minimal) !void {
    g_environ = init.environ;

    var debug_allocator: std.heap.DebugAllocator(.{}) = .init;
    defer _ = debug_allocator.deinit();
    const allocator = debug_allocator.allocator();

    var threaded = std.Io.Threaded.init(allocator, .{});
    defer threaded.deinit();
    const io = threaded.io();

    var file_storage = tz.Storage.File.init("feature_demo.session");

    const client = try tz.Client(handlers).init(allocator, .{
        .api_id = try std.fmt.parseInt(i32, init.environ.getPosix("TZ_API_ID") orelse usage(), 10),
        .api_hash = init.environ.getPosix("TZ_API_HASH") orelse usage(),
        .bot_token = init.environ.getPosix("TZ_BOT_TOKEN") orelse usage(),
        .storage = file_storage.storage(),
    });
    defer client.deinit();

    try client.run(io);
}

fn usage() noreturn {
    std.log.err("usage: TZ_API_ID=<id> TZ_API_HASH=<hash> TZ_BOT_TOKEN=<token> ./feature_demo", .{});
    std.process.exit(1);
}
